---
version: "3"

tasks:
  check:fmt:
    cmd: go fmt ./...

  check:vet:
    cmd: go vet ./...

  check:lint:
    cmd: golangci-lint run

  check:
    deps:
      - check:fmt
      - check:vet
      - check:lint

  server:build:ci:
    deps:
      - check
      - server:build

  server:build:
    cmd: >-
      go build \
        -o tmp/mycorp-server \
        cmd/server/main.go

  server:run:
    deps:
      - check
    cmd: >-
      air \
        --build.cmd "go build -o tmp/server cmd/server/main.go" \
        --build.entrypoint "tmp/server" \
        --build.include_dir "cmd,internal,pkg,scenarios" \
        --build.include_ext "go,tpl,tmpl,html,yaml"
    desc: Run local server

  client:test:
    deps:
      - check
    env:
      MYCORP_CLI_URL: http://127.0.0.1:8080
    cmd: >-
      go run cmd/client/main.go \
        dns create
